# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
author: Principles of Programming Group
name: PoP CMU
title: Principles of Programming Group - Carnegie Mellon Univeristy
email: pop-group@cs.cmu.edu
maintainer: Feras Saad
description: Principles of Programming Group at Carnegie Mellon Univeristy
footer_text:

url: cs.cmu.edu  # the base hostname & protocol for your site
baseurl: /~pop # the subpath of your site, e.g. /blog/

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username:
google_analytics:
youtube_channel:
rss:  # notes rss

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  announcements:
    defaults:
      layout: post
    output: true
    permalink: /announcements/:path/
  talks:
    sort_by: date
    output: true
    permalink: /talks/:path/

announcements_limit: 5

defaults:
  -
    scope:
      path: ""
      type: "talks" # a collection in your site, in plural form
    values:
      layout: "talk"
      logo: "cmu-logo.png"
      

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: rouge

# Includes & excludes
include: ['_pages']
exclude:
  - vendor
  - Gemfile*
  - deploy.sh
  - README.md

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jemoji

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.10.1"
anchorjs_version: "3.2.2"
latexjs_version: "0.11.1"
future: true

theme: jekyll-theme-slate
